language: c
dist: trusty
sudo: false

branches:
  only:
  - /.*/
#  - master
#  - develop

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran doxygen graphviz

before_install:
  - test -n $CC && unset CC
  - test -n $FC && unset FC
  - test -n $CXX && unset CXX
  - test -n $CPPFLAGS && unset CPPFLAGS
  - test -n FCFLAGS && unset FCFLAGS

before_script:
  - export GEOFLOW_DIR=`pwd`
  - cd ..
  - export BASE_DIR=`pwd`
  - export CC=mpicc
  - export FC=mpif90
  - export CXX=mpicxx
  - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
  - tar -xzf boost_1_72_0.tar.gz
  - cd boost_1_72_0
  - export TOOLSET=gcc
  - export MPI_WRAPPER=${CXX}
  - export NPROC=12
  - export INSTALL_LOC=`pwd`/gcc
  - export BUILD_LIBS=mpi,serialization
  - ./bootstrap.sh --with-toolset=${TOOLSET} --with-libraries=${BUILD_LIBS} --prefix=${INSTALL_LOC}
  - ./b2 -j ${NPROC} install
env:
  global:
    - CC=mpicc
    - CXX=mpicxx
    - FC=mpif90
    - CPPFLAGS='-I/usr/include'
    - CFLAGS='-std=c99'
    - LDFLAGS='-L/usr/lib'
  
script:
  - pwd
  - cd ${GEOFLOW_DIR}
  - pwd
  - mkdir -p build
  - cd build
  - pwd
  - ls
  - export BOOST_ROOT=${BASE_DIR}/boost_1_72_0/gcc
  - cmake -DBOOST_ROOT=boost_1_72_0/gcc -DBoost_INCLUDE_DIR=${BOOST_ROOT}/include ..
#  - make VERBOSE=1
#  - make tests VERBOSE=1
#  - make test VERBOSE=1
